endpoints.health.sensitive: false

management:
  health.defaults.enabled: false
  port: 2442
  security.enabled: false

server:
  port: 8080
  context-path: /kdt

kdt:
  producer:
    enabled: true
  consumer:
    enabled: true
    idleThreshold: 1800000
  environments:
    customUrlsEnabled: true
    supportedEnvironments:
      - id: local
        name: Local
        kafkaHost: localhost:9092
        schemaUrl: http://localhost:8081

---
spring.profiles: local

management:
  health.defaults.enabled: false
  port: 10000
  security.enabled: false

server:
  port: 10000
  context-path: /kdt

logging.level.com.de314: DEBUG